// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function() {
    return function(req, res, next) {
      if (/.*\.(ttf|eot|woff|svg)$/.test(req._parsedUrl.pathname)) {
        res.setHeader('Access-Control-Allow-Origin', '*');
      }
      return next();
    };
  };

}).call(this);
