// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function() {
    return function(req, res, next) {
      var _this = this;
      req.url = req.url.replace(/(.+\/)(\d+(\.\d+)*\/)(prd\/)(.*)/, function() {
        return arguments[1] + arguments[4] + arguments[5];
      });
      return next();
    };
  };

}).call(this);
